name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Pack
        run: dotnet pack src/WinUI3.Diagnostics/WinUI3.Diagnostics.csproj -c Release --no-build -o artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: artifacts/*.nupkg