name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          # Uncomment if builds fail due to unresolved version (pre-GA scenarios)
          dotnet-quality: 'ga'
          cache: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      # Optional: run tests if present
      - name: Test
        if: hashFiles('**/*Tests*.csproj') != ''
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Pack
        run: dotnet pack src/WinUI3.Diagnostics/WinUI3.Diagnostics.csproj -c Release --no-build -o artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: artifacts/*.nupkg
